name: lab06-mytest
on:
  push:
    branches:
      - 'lab06-*'
defaults:
  run:
    working-directory: lab06-mytest/solution
jobs:
  c:
    uses: ./.github/workflows/common-02.yml
    with:
      working_directory: lab06-mytest/solution
      simple_compilation_name: mytest_main
      simple_compilation_extra_tus: mytest.cpp
      clang_tidy_extra: -extra-arg=-I.
      max_lines: 400
