name: lab04-tic-tac-toe
on:
  push:
    branches:
      - 'lab04-*'
defaults:
  run:
    working-directory: lab04-tic-tac-toe/solution
jobs:
  c:
    uses: ./.github/workflows/common-02.yml
    with:
      working_directory: lab04-tic-tac-toe/solution
      run_test_data_extra_args: ./tic-tac-toe
      clang_tidy_extra: -extra-arg=-Iinclude
      cppcheck_extra: -Iinclude
      skip_ubuntu_libcxx: true  # Ubuntu's Boost.Filesystem is built against libstdc++
      max_lines: 500
